MADE HW2
anasteizha/prep_course_c_cpp pull request #2
Opened 2021-10-24 16:35 UTC by kuzkuss

Меня зовут Кузнецова Анастасия
Я студентка Подготовительного курса технопарка по C/C++
Высылаю на проверку ДЗ№2

2021-10-25 11:31 UTC, ArtemSarmini requested changes

2021-11-21 15:23 UTC, leshiy1295 requested changes
Пока что просто разнесли функции и структуры по модулям, но сами функции и ещё декомпозировать и декомпозировать!
Можете в течение недели поправить и прислать ментору на повторную проверку!

2021-12-25 02:04 UTC, ArtemSarmini requested changes

2022-01-06 21:38 UTC, leshiy1295 reviewed
Многое сделано, но для себя рекомендую кардинально переработать эту программу, чтобы довести её до идеального состояния. Тут ещё много чего можно сделать

2022-09-28 08:52 UTC, closed without merging